# [VIEWER MAKEFILE]
# 1. 指向原始 rai 库的绝对路径
BASE = /home/leslie/Projects/VLM_LGP/rai

# 2. 目标文件名


# 3. 源文件对象 (对应 view_scene.cpp)
OBJS = main.o

# 4. 依赖库 (Viewer 只需要这些基础库)
DEPEND = Core Kin Gui Geo KOMO LGP Logic Optim Algo

# 5. 引入构建规则
include $(BASE)/_make/generic.mk
